### ISSUE TITLE
Error installing deb package

### ISSUE THREAD

**Issue by ramoncasares** [lahcim8/lltex#1]
I am using Debian Buster (stable).
Package `mmtex_20210102_amd64` tries to overwrite the TeX Live `luatex` binary, and fails.

<pre>
# apt install ./mmtex_20210102_amd64.deb
...
Unpacking mmtex (20210102) ...
...
trying to overwrite '/usr/bin/luatex', which is also in package texlive-binaries 2018.20181218.49446-1
</pre>

Just calling it `mmluatex` solves the problem.

**Comment by vlasakm** [comment]
Hello,

this seems like a good idea. Not only does this allow to have multiple TeX distributions installed without collision, but also reflects the fact that both the `luatex` engine and `optex` formats are (slightly) modified.

Hence I renamed `luatex` to `mmluatex` and `optex` to `mmoptex`.

Didn't have the time to document this properly, but mmtex has gone through a transition and no longer includes luatex plain format. That means that while `mmluatex` binary is provided it most likely will fail (if not used as `iniluatex`):

```
I can't find the format file `mmluatex.fmt'!
```

Also Type 1 Latin Modern and AMS fonts are also no longer provided. This means that unlike normal OpTeX a `\fontfam` (like `\fontfam[LMfonts]`) needs to be essentially the first command in the document - there is no preloaded font, nor a fallback. This also requires reording of commands in some OpTeX demo documents, because a command like `\letter` is dependent on having fonts initialized. And for these demo documents in particular TeX Gyre fonts need to be installed - depending on your setup this can be done by installing `fonts-texgyre` package.

Please let me know if the latest release (v20210105) works for you and also whether you find the absence of plain luatex a big loss, when OpTeX is available.

**Comment by ramoncasares** [comment]
Now the package (v20210105) installs itself without any problem. And it answers with its version:
<pre>$ mmluatex --version
This is LuaTeX, Version 1.12.0 (mmtex)
...
</pre>
Perhaps it will be helpful to include the mmtex version, `(mmtex v20210105)` .

It also responds corretly to `mmluatex --help`. However, it fails on `op-demo.tex`, and without any argument.
<pre>$ mmluatex --help
Usage: luatex --lua=FILE [OPTION]... [TEXNAME[.tex]] [COMMANDS]
   or: luatex --lua=FILE [OPTION]... \FIRST-LINE
   or: luatex --lua=FILE [OPTION]... &FMT ARGS
  Run LuaTeX on TEXNAME, usually creating TEXNAME.pdf.
...
$ mmluatex op-demo.tex
Illegal instruction
$ mmluatex
Illegal instruction
</pre>

Do I need to specify a `--lua=FILE` argument? If so, which one?

**Comment by vlasakm** [comment]
I added mmtex version information to the message. It is determined by git and for tags like `v20210105` should show them and for development versions something like `v20210105-2-g205f2e4`.

The `Illegal instruction` error was caused by wrong optimization arguments, that caused usage of not always available CPU instructions.

Try package `mmtex_20210105.2.ga60077d_amd64.deb` which I appended to last release. I will make a release when this will be sorted out.

No special argument is required:

```
$ mmoptex op-demo
This is LuaTeX, Version 1.12.0 (mmtex v20210105-2-ga60077d)
(./op-demo.tex
This is OpTeX (Olsak's Plain TeX), version <Beta 0.18 Dec.2020>
(/usr/share/mmtex/tex/optex/f-lmfonts.opm
FONT: [Latin Modern] -- \LMfonts (TeX Gyre fonts based on Coputer Modern)
 mods:{\roman \sans \quotset \ttset \ttprop \ttlight \ttcond \upital \dunhill s
ubmods:\caps \slant \nbold \bolder } vars:{\rm \bf \it \bi \tt } math:{LM}
MATH-FONT: "[latinmodern-math]" -- unicode math prepared.
(/usr/share/mmtex/tex/optex/unimath-codes.opm
Uni math codes <2020-11-13>
(/usr/share/mmtex/tex/optex/mathclass.opm)
(/usr/share/mmtex/tex/optex/unimath-table.opm)))
l.17> WARNING: \maketoc -- data unavailable, TeX me again.
l.46> WARNING: pg-label [my-eq] unknown. Try to TeX me again.
l.47> WARNING: label [my-tab] unknown. Try to TeX me again.
l.48> WARNING: label [tab-sec] unknown. Try to TeX me again.
l.48> WARNING: label [my-pic] unknown. Try to TeX me again.
l.49> WARNING: pg-label [my-pic] unknown. Try to TeX me again.
[1] [2<./op-ring.png>]
l.127> WARNING: Rerun to get references right.
)</usr/share/texmf/fonts/opentype/public/lm/lmroman7-regular.otf></usr/share/mm
tex/fonts/type1/rsfs10.pfb></usr/share/texmf/fonts/opentype/public/lm/lmroman9-
bold.otf></usr/share/texmf/fonts/opentype/public/lm-math/latinmodern-math.otf><
/usr/share/texmf/fonts/opentype/public/lm/lmroman10-bold.otf></usr/share/texmf/
fonts/opentype/public/lm-math/latinmodern-math.otf></usr/share/texmf/fonts/open
type/public/lm/lmmono9-regular.otf></usr/share/texmf/fonts/opentype/public/lm/l
mroman9-regular.otf></usr/share/texmf/fonts/opentype/public/lm/lmroman12-bold.o
tf>
Output written on op-demo.pdf (2 pages, 725647 bytes).
Transcript written on op-demo.log.


$ mmoptex op-demo
This is LuaTeX, Version 1.12.0 (mmtex v20210105-2-ga60077d)
(./op-demo.tex
This is OpTeX (Olsak's Plain TeX), version <Beta 0.18 Dec.2020>
(./op-demo.ref) (/usr/share/mmtex/tex/optex/f-lmfonts.opm
FONT: [Latin Modern] -- \LMfonts (TeX Gyre fonts based on Coputer Modern)
 mods:{\roman \sans \quotset \ttset \ttprop \ttlight \ttcond \upital \dunhill s
ubmods:\caps \slant \nbold \bolder } vars:{\rm \bf \it \bi \tt } math:{LM}
MATH-FONT: "[latinmodern-math]" -- unicode math prepared.
(/usr/share/mmtex/tex/optex/unimath-codes.opm
Uni math codes <2020-11-13>
(/usr/share/mmtex/tex/optex/mathclass.opm)
(/usr/share/mmtex/tex/optex/unimath-table.opm))) [1] [2<./op-ring.png>])</usr/s
hare/texmf/fonts/opentype/public/lm/lmroman7-regular.otf></usr/share/mmtex/font
s/type1/rsfs10.pfb></usr/share/texmf/fonts/opentype/public/lm/lmroman9-bold.otf
></usr/share/texmf/fonts/opentype/public/lm-math/latinmodern-math.otf></usr/sha
re/texmf/fonts/opentype/public/lm/lmroman10-bold.otf></usr/share/texmf/fonts/op
entype/public/lm-math/latinmodern-math.otf></usr/share/texmf/fonts/opentype/pub
lic/lm/lmmono9-regular.otf></usr/share/texmf/fonts/opentype/public/lm/lmroman9-
regular.otf></usr/share/texmf/fonts/opentype/public/lm/lmroman12-bold.otf>
Output written on op-demo.pdf (2 pages, 727260 bytes).
Transcript written on op-demo.log.
```

**Comment by ramoncasares** [comment]
OK. Now it works!

Regarding not having the plain format, it is not really a problem as long as it can be generated, if needed. I will do it, because all my documents are in plain TeX, and I want to see if they can be redone, but I like very much your minimalist approach and, as you said, plain is not modern.

I close this issue. Thanks and best regards,
   Ramón

**Comment by vlasakm** [comment]
I must warn you that while generating plain format can be done (as the engine is there), I am afraid that is no longer that feasible in mmtex. After removing plain and most of fonts there are a lot of missing pieces for generating TeX Live's plain LuaTeX format. Also mmtex was not really designed to support not included formats - for example the files required to build the format were not distributed.

These are the things that need attention:

### OpenType font support

In TeX Live's plain the OpenType font support is not really a part of the format. `luaotfload` has to be loaded for essentially all documents (`\input luaotfload.sty`). While the `luaotfload` package is included in mmtex, the smal `.sty` wrapper is not. It can be replaced by:

```
\directlua{
	require('luaotfload')
	luaotfload.main()
}
```

But luaotfload itself depends on Lua callback handling code from LaTeX kernel (`ltluatex.{lua,tex}`). Though I have written  [`optex.lua`](https://github.com/olsak/OpTeX/blob/master/optex/base/optex.lua), which can be used as a replacement.

### OpenType math

There is no support for OpenType math in LuaTeX plain. The solution here would probably be to use `uni-math.tex` (https://tex.stackexchange.com/questions/308749/unicode-math-at-tex-primitive-level) from Olšák's `csplain`. But I am not sure about the maintance status of that.

### Hyphenation pattern loading

LuaTeX plain uses `etex.src` and `luatex-hyphen.lua`'s mechanisms for loading hyphenation patterns. These are also no longer provided. The solution here can be to just `\input hyph-es` (or similiar for other langauges) at runtime (not format generation time!). This loads both the patterns and exceptions. Although `\language`, `\lefthyphenmin` and `\righthyphenmin` also have to be set prior to this.
