### ISSUE TITLE
Error with "meson" when compiling from source

### ISSUE THREAD

**Issue by tibinecas** [lahcim8/lltex#6]
Im using Tails 5.22 OS, a Debian 11 based.

After using 

`meson setup builddir --prefix ~/.mmtex --buildtype release`

I get 3 warnings and 1 error in the following log:

```
meson.build:19: WARNING: Passed invalid keyword argument "env".
WARNING: This will become a hard error in the future.
WARNING: Unknown keyword arguments in target mmoptex.fmt: env
meson.build:37:0: ERROR: Unknown function "install_symlink".
```

[meson-log.txt](https://github.com/vlasakm/mmtex/files/14579489/meson-log.txt)

**Comment by vlasakm** [comment]
The link to `meson-log.txt` unfortunately doesn't work for me (Error 404 Not Found).

I am not sure about the `env` argument - I haven't seen the warning before.

But the fact that you are using Debian and `install_symlink` seems to be missing implies that the meson version you have is older than is required currently :(. I rememer that I had to remove some older distribution releases, like Debian 11 from the [Open Build Service](https://build.opensuse.org/project/show/home:lahcim8), because they had old meson versions.

Not that long ago, I was using a custom solution for symlinking, instead of this new built-in thing. Are you able to install a newer version of meson easily, or should I just restore the previous behavior until the new meson versions become common enough?

**Comment by vlasakm** [comment]
On Debian 12 I already have new enough meson (1.0.1), but I was able to install a recent version (1.4.0) in a temporary python virtual environment:

```
sudo apt install python3.11-venv
python3 -m venv /tmp/venv
source /tmp/venv/bin/activate
python -m pip install --upgrade pip meson
meson --version
```

Could that work for you?

**Comment by vlasakm** [comment]
For now I added a commit which documents the minimum required meson version (0.61), which should at least give a more descriptive error message.

**Comment by tibinecas** [comment]
> The link to `meson-log.txt` unfortunately doesn't work for me (Error 404 Not Found).
> 
> I am not sure about the `env` argument - I haven't seen the warning before.
> 
> But the fact that you are using Debian and `install_symlink` seems to be missing implies that the meson version you have is older than is required currently :(. I rememer that I had to remove some older distribution releases, like Debian 11 from the [Open Build Service](https://build.opensuse.org/project/show/home:lahcim8), because they had old meson versions.
> 
> Not that long ago, I was using a custom solution for symlinking, instead of this new built-in thing. Are you able to install a newer version of meson easily, or should I just restore the previous behavior until the new meson versions become common enough?

You were right! I updated meson from version 0.56.2-1 to 1.0.1-5 using

`sudo apt install meson=1.0.1-5`

Thank you!

**Comment by vlasakm** [comment]
Great! I am glad it helped.
