### ISSUE TITLE
Font \_ten_tenrm=nullfont at 10pt not loadable

### ISSUE THREAD

**Issue by tibinecas** [lahcim8/lltex#7]
Im using Debian 11.

After compiling with test.tex:

`abc \bye`

I've obtained:

```
! Font \_ten_tenrm=nullfont at 10pt not loadable: metric data not found or bad.
[1
Missing character: There is no a (U+0061) in font nullfont!
Missing character: There is no b (U+0062) in font nullfont!
Missing character: There is no c (U+0063) in font nullfont!
Missing character: There is no 1 (U+0031) in font nullfont!
]
WARNING l.3: Unicode font was not loaded.
```

When I use \fontfam[lm] at the beginning of the preamble, the result is:

```
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: File not found: "lmroman10-regular".
WARNING l.7: Family [Latin Modern] skipped, font "[lmroman10-regular]" not found.
Missing character: There is no a (U+0061) in font nullfont!
Missing character: There is no b (U+0062) in font nullfont!
Missing character: There is no c (U+0063) in font nullfont!
Missing character: There is no 1 (U+0031) in font nullfont!
```

The PDF is always blank.

**Comment by vlasakm** [comment]
```
abc
\bye
```

Is not expected to work. I mention it briefly in the README:

> Note that no implicit fonts are set. You will get errors if you don't set a font family.

I don't like the situation, but OpTeX defaults to using the old style Type 1 fonts, which I think is bad, because it works best only with OpenType fonts - the old style fonts are there only for some trivial testing. In my mind it is preferable to get no document at all, rather than potentially half broken document, because of classic 8-bit TeX issue like no real support for Unicode, etc.

Defaulting to `\fontfam[lmfonts]` is also not that easy, since I don't want to include fonts in the mmtex distribution, as that's problematic with regards to licenses, etc. Also having a dependency on Linux distribution provided latin modern fonts is not always possible, since the font is not separately available in all repositories.

```
\fontfam[XXX]
abc
\bye
```

Is supposed to work, _if_ you have the `XXX` font installed. Because no fonts are provided, you have to install the fonts manually. On Debian, the latin modern fonts can be installed through package `fonts-lmodern`. The package from open build service does have dependency on the package, so you would get it [automatically](https://build.opensuse.org/package/view_file/home:lahcim8/mmtex/debian.control?expand=1), but since you installed manually, you have to also get the latin modern font dependency manually.


(Just a side note, I thought about using [Tectonic TeX Live bundles](https://github.com/tectonic-typesetting/tectonic-texlive-bundles/) to allow mmtex to transparently get all files from TeX Live, including fonts. But that would require something more advanced than just redistributing LuaTeX, OpTeX and a few related packages, so that is more of a very long term project idea.)

**Comment by tibinecas** [comment]
Understand. I downloaded fonts-lmodern manually.

**Comment by vlasakm** [comment]
As unfortunate as it is, I don't have a "nice" solution for getting fonts working automatically, and am putting the burden of installing fonts on users.

Closing this for now, though feel free to raise any other issues.
